spring.data.mongodb.host=172.28.0.10
spring.data.mongodb.port=27017
spring.data.mongodb.database=paymentdb

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
